# DOC: https://github.com/rhazdon/hugo-theme-hello-friend-ng
#      https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/exampleSite/config.toml

baseURL = "https://nofreedisk.space/"
languageCode = "en-us"
title = "nofreedisk.space"
baseurl = "/"
theme = "hello-friend-ng"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "docs"

DefaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 20  # Maximum number of items in the RSS feed.

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
  name = "dauliac"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by dauliac"
  keywords = "homepage, blog, science, informatics, development, programming, cloud, cicd, docker, francais"
  images = [""]
  homeSubtitle = "par dauliac: junions, devops et admin-sys"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "email"
    url  = "mailto:dauliac@protonmail.com"
  [[params.social]]
    name = "codepen"
    url  = "https://codepen.io/Dauliac"
  [[params.social]]
    name = "github"
    url  = "https://github.com/dauliac"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/julien-dauliac-26a577135/"

[languages]
  [languages.en]
    subtitle  = "Just an IT blog"
    weight    = 1

  [languages.fr]
    subtitle  = "Juste un blog d'IT"
    weight    = 2

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
