baseURL = "http://nofreedisk.space/"
languageCode = "en-us"
title = "IT Bordeaux blog"
baseurl = "/"
theme = "hello-friend-ng"
publishDir = "docs"

DefaultContentLanguage = "en"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by dauliac"
  keywords = "homepage, blog, science, informatics, development, programming, cloud, cicd, docker, francais"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Nofreedisk.Space blog"
    subtitle = "just a dev's blog"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "just a dev's blog from Bordeaux"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
  [languages.fr]
    title = "Nofreedisk.Space blog"
    subtitle = "Juste un blog de dev."
    keywords = ""
    copyright = ""
    readOtherPosts = "lire les autres posts"

    [languages.fr.params.logo]
      logoText = "juste un blog de dev bordelais"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "à propos"
        name = "À propos"
        url = "/about"
      [[languages.fr.menu.main]]
        identifier = "aperçu"
        name = "Aperçu"
        url = "/showcase"


# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
